export { default as SearchBar } from './SearchBar/SearchBar'
export { default as Image } from './Image/Image'
export { default as ClosedNameContainer } from './ClosedNameContainer/ClosedNameContainer'
export { default as PersonDetailCard } from './PersonDetailCard/PersonDetailCard'
export { default as FavoritesList } from './FavoritesList/FavoritesList'